### ISSUE TITLE
setItem is not a function

### ISSUE THREAD

**Issue by wincod75** [mCodex/react-native-sensitive-info#234]
Error: TypeError: _reactNativeSensitiveInfo.default.setItem is not a function

`
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-sensitive-info": "^6.0.0-alpha.5",`

**Comment by wincod75** [comment]
Downgraded to 5.5.8 and reinstalled pods, works fine now. Should probably not use stuff like this: `npm install react-native-sensitive-info@next` in your docs unless the alpha version has been tested.

**Comment by mCodex** [comment]
First of all, thanks for your report.

I've just created a new project from scratch and tested what you have said and I can confirm that v6's setItem is working on iOS. Plus, there is an example project on master which uses v6 and you can confirm that setItem is also working there.

![Simulator Screen Shot - iPhone 11 - 2020-09-02 at 09 07 45](https://user-images.githubusercontent.com/5920613/91979671-7d84f280-ecfc-11ea-8823-e5344617798b.png)

```js
<Button
    title="Press me"
    onPress={async () => {
        await SInfo.setItem('key', 'val', {
            sharedPreferencesName: 'mySharedPrefs',
            keychainService: 'myKeychain',
        });
        console.log(
            await SInfo.getItem('key', {
                sharedPreferencesName: 'mySharedPrefs',
                keychainService: 'myKeychain',
            }),
        );

        return Alert.alert('Success', 'Data successfully saved');
    }}
/>
```

So, again thank you for your report. However, next time try to be more friendly since RNInfo and many other libraries that you use are open source and anyone can submit PRs to fix issues or even improve docs.

Have a nice day.

**Comment by wincod75** [comment]
@mCodex Greetings! I meant no disrespect. Also, I did not test any version between 5.5.8 and 6.0.0-alpha.5, but the alpha version did in fact break my app. I couldn't even log the import. There's always room for error of course, but as mentioned, once I downgraded it worked like a charm.

**Comment by jllopiz90** [comment]
Hi @mCodex, thanks for the effort put in this library, I'm trying to store something in the device in a secure way so I tried with this package but I'm getting this error as well, using version `6.0.0-alpha.8`. Since for you is working in the example app, can you perhaps give me a direction what may be wrong in my end? Perhaps is related to the linking, although I already ran pod install and verify that react-native-sensitive-info is in the Pods folder, I hit a similar issue with react-native-keychain and that's why I tried this one but hit the same wall.
