### ISSUE TITLE
Using Conceal for encryption implementation

### ISSUE THREAD

**Issue by AlanFoster** [mCodex/react-native-sensitive-info#28]
Thanks for the great library!

Out of interest, [react-native-keychain](https://github.com/oblador/react-native-keychain) currently makes use of Facebook's [conceal](https://github.com/facebook/conceal) - would there be any advantage for react-native-sensitive-info to also make use of this library?

**Comment by mCodex** [comment]
Hello @AlanFoster, thank you!! I didn't know about Facebook's conceal. 

We can use Facebook's conceal as well, but we've to see if is compatible with Android 16+... Maybe It is, because Facebook must use this. Also, we are looking for better privacy/encryption ways on our library.

On the other hand, It would be a breaking change for react-native-sensitive-info, but I believe there is a way to implement Facebook's conceal and make this work without being a breaking change. 🤔
