### ISSUE TITLE
Using the Keystore on Android 4.3+

### ISSUE THREAD

**Issue by denissb** [mCodex/react-native-sensitive-info#31]
I am proposing a feature request :)

Since Android 4.3 the [Android Keystore](https://developer.android.com/training/articles/keystore.html) was introduced. Do you have any plans on switching to that for Android (or making it an option), since it's more secure for storing sensitive data like tokens and passwords?

**Comment by mCodex** [comment]
Hello @denissb, we have already this feature, but it is in another branch: https://github.com/mCodex/react-native-sensitive-info/tree/keystore

Unfortunately, we don't have any plans to release it in our master because react-native supports Android 16+ and using Android Keystore requires RNSensitiveInfo using Android 18+ 😢 So, we wouldn't cover all devices supported by react-native.

**Comment by denissb** [comment]
Thank's for the information, using shared preferences should still be secure enough unless the application has root access. I will check the branch if I will desperately need this feature.

**Comment by denissb** [comment]
@mCodex - sorry for coming back to this, but why don't you apply it conditionally only if the Android version is 18+?

**Comment by mCodex** [comment]
@denissb, I can try, but when I import Android Keystore methods I've to upgrade RNSensitiveInfo to Android 18+ 😞

**Comment by denissb** [comment]
I see, so react native detects usage of that Keystore package in Java and dose not allow to keep the same minimum version? (16+)

**Comment by mCodex** [comment]
Not React, but Android itself :/

**Comment by Palisand** [comment]
@mCodex [react-native-keychain](https://github.com/oblador/react-native-keychain#new-200-rc-with-improved-android-implementation) uses Facebook Conceal for 16 - 22 and keystore for 23+.
