### ISSUE TITLE
Is it safe to store JWT-Token?

### ISSUE THREAD

**Issue by j3rin** [mCodex/react-native-sensitive-info#40]
Can I store JWT Tokens? is this safe to do ?

**Comment by mCodex** [comment]
@j3rin , you can say so. Android devices has more problems than iOS, because shared preferences doesn't store securely, also if Android is rooted values can be easily retrieved. On the other hand, if you want to store your tokens using [Android keystore](https://developer.android.com/training/articles/keystore.html?hl=pt-br) and you don't mind to update your gradle files to support only Android SDK 18 + we have a [branch](https://github.com/mCodex/react-native-sensitive-info/tree/keystore) for it. 

If you want more security you can use our master branch and store values using Fingerprint, TouchID (thanks to @evollu) feel free to use :)

**Comment by j3rin** [comment]
I'm building IOS app, It's better than using AsyncStorage?

**Comment by mCodex** [comment]
Yes, as you can see in [AsyncStorage's description](https://facebook.github.io/react-native/docs/asyncstorage.html):

`"AsyncStorage is a simple, unencrypted, asynchronous, persistent, key-value storage system that is global to the app."
`

**Comment by evollu** [comment]
Just an bit more info, if you want to protect info from jailbroken device, keystore itself won't help. Hackers can extract keys from keystone and decrypt values

**Comment by j3rin** [comment]
so all the data is stored in keychain for IOS devices? sorry for all the questions, thank you guys!

**Comment by evollu** [comment]
Yes
