### ISSUE TITLE
Fingerprint is not properly implemented for Android

### ISSUE THREAD

**Issue by soumyamishra89** [mCodex/react-native-sensitive-info#79]
When i access setItem or getItem with touchID = true,
i get get the following error: **The callback getItem() exists in module RNSensitiveInfo, but only one callback may be registered to a function in a native module.** 
This happens on some of the phone i test with. But the issue is resolved when I removed the line pm.reject(String.valueOf(errorCode), errString.toString()); from RNSensitiveInfoModule (line 257 and line 337)in the android code for your module. after removing this line the app worked as expected and i was able to set and get items without issues. This is strange as onAuthenticationError should not be evoked if fingerprint works properly.

Could you have a look into this.

**Comment by ycai2** [comment]
I think this happens very likely (although maybe more than) due to more than one processes of `getItem()` pending. Currently, without additional handling in this library, the easiest way is to make sure you don't make additional calls to `getItem()` until the first one resolves or until you call `cancelFingerprintAuth()`.
